### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by CoolCatB** [Stog/homebridge-fronius-inverter#2]
When I try to run your install command, i get the below error:
sudo npm install -g homebridge-fronius-inverter
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebridge-fronius-inverter - Not found
npm ERR! 404 
npm ERR! 404  'homebridge-fronius-inverter@latest' is not in the npm registry.

Should I be using a different install method?

**Comment by Stog** [comment]
Yeah my bad - looks like I had a typo issue with the npm package name this should be fixed now.

**Comment by CoolCatB** [comment]
It works now. Thank you!
