### ISSUE TITLE
Plugin config help needed

### ISSUE THREAD

**Issue by nellywelly** [Stog/homebridge-fronius-inverter#8]
Plugin config help needed
Id like to use the :Fronius Inverter" plugin but having difficulties pulling data from the unit,

Im using the supplied copy and pasted config for each acsessory. And they show up in homekit. but there is no data displayed.

The config is

"accessory": "FroniusInverter", "name": "Generation", "ip": "xxx.xxx.xxx.xxx", "inverter_data": "P_PV" }

My inverter IP starts with 139.xxx.xxx.xxx

If anyone has any idea. That would be awesome!

**Comment by maddogeco** [comment]
An internal ip address starting with 139 in a home network seems odd. 
Assuming the inverter is on your home network and posting data to fronius's solar web, download the Fing app on your smart phone and run a network scan this should reveal the internal ip address. Most likely it'll start with 192.168.x.x or maybe 10.x.x.x 

If it's not on your network, the inverter can create it's own hotspot which you can log into with a phone or laptop and enter your WiFi details via its Web admin page. This is turned on via the on screen menu under settings access point. Going from memory. 
Hope that helps

**Comment by nellywelly** [comment]
> An internal ip address starting with 139 in a home network seems odd.
> Assuming the inverter is on your home network and posting data to fronius's solar web, download the Fing app on your smart phone and run a network scan this should reveal the internal ip address. Most likely it'll start with 192.168.x.x or maybe 10.x.x.x
> 
> If it's not on your network, the inverter can create it's own hotspot which you can log into with a phone or laptop and enter your WiFi details via its Web admin page. This is turned on via the on screen menu under settings access point. Going from memory.
> Hope that helps

Thanks so much for your help.
I followed your instructions to find the actual IP address.
Got it all up and working now!
Automated solar production to house heating routines.
Awesome!
Thanks so much!
